#!/bin/sh
# Copyright 2014 Frank Pavageau
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ $# = 0 ]; then
  echo "Usage: jtgrep [-i] [-v] PATTERN [FILE...]"
  echo "    -c Replace normal output by a count of matching threads for each input file"
  echo "    -h Suppress the prefixing of file names on output when counting"
  echo "    -H Print the file name for each match when counting"
  echo "    -i Ignore case distinctions in the pattern"
  echo "    -o Fold the output by only showing the first matching part of the stack"
  echo "    -v Invert the sense of matching, to select non-matching threads"
  exit 1
fi

COUNT=0
IGNORECASE=0
INVERT=0
MATCH_ONLY=0
# Possible values: -1 = default behavior, 0 = never show the file name, 1 = always show the file name
SHOWFILE=-1

while getopts chHiov PARAM; do
  case $PARAM in
    c) COUNT=1;;
    h) SHOWFILE=0;;
    H) SHOWFILE=1;;
    i) IGNORECASE=1;;
    o) MATCH_ONLY=1;;
    v) INVERT=1;;
  esac
done
shift $(($OPTIND - 1))

if [ $MATCH_ONLY = 1 ] && [ $INVERT = 1 ]; then
  echo "Incompatible options: -o -v" 1>&2
  exit 1
fi

PATTERN=$1
shift

awk -v pattern="$PATTERN" -v doCount=$COUNT -v invert=$INVERT \
    -v matchOnly=$MATCH_ONLY -v showFile=$SHOWFILE -v IGNORECASE=$IGNORECASE '
BEGIN {
  # Possible values:
  # - -1: outside of a thread
  # - 0: thread has not not matched yet
  # - 1: thread matched
  m = -1
  # Convert to a proper integer: the string "0" does not have the same meaning
  # as the integer 0 (i.e. it is true, not false).
  IGNORECASE = int(IGNORECASE)
}

# Track the changes of current file
currentFile != FILENAME {
  if (currentFile) {
    printFileCount(currentFile)
  }
  fileCount++
  currentFile = FILENAME
  count = 0
  threadCount = 0
}

# Print text blocks outside of a thread
/^[a-zA-Z0-9]/ {
  printThread()
  if (!matchOnly) { condPrint($0) }
  m = -1 # Set the "outside of thread" context
}

# Print empty lines outside of a thread
m < 0 && !matchOnly && /^$/ { condPrint($0) }

# Start a new thread
/^"/ {
  printThread()
  thread = ""
  m = 0
  stackMatch = 0
  threadCount++
}

# Accumulate the lines for the current thread
m >= 0 {
  if (thread) {
    if (!matchOnly ||
        (!stackMatch &&
         $1 == "at" &&
         ((invert && $0 !~ pattern) ||
          (!invert && $0 ~ pattern)))) {
      stackMatch = 1
      thread = thread "\n" $0
    }
  } else { thread = $0 }
}

# Try to match the current thread with the pattern
m == 0 && $0 ~ pattern {
  m = 1
  count++
}

END {
  printThread()
  printFinalCount()
}

function printThread() {
  if ((!invert && m > 0 && (!matchOnly || stackMatch)) || (invert && m == 0)) {
    condPrint(thread)
  }
}

function condPrint(line) {
  if (!doCount) {
    print line
  }
}

function printFileCount(file) {
  if (doCount) {
    realCount = invert ? threadCount - count : count
    if (file && showFile != 0) {
      print file ":" realCount
    } else {
      print realCount
    }
  }
}

function printFinalCount() {
  # Just like grep: if you count on a single file, you get the count and if
  # you count on multiple files, you get each file name and the count.
  if (fileCount > 1 || showFile > 0) {
    printFileCount(currentFile)
  } else {
    printFileCount()
  }
}
' $@
